routing:
  API:
    items: "/users/:login_id/items"
    contacts: "/users/:login_id/items/:item_id/types/:type_id/contacts"
    contacts_bis: "/users/:login_id/contacts" 
    pictures: "/users/:login_id/items/:item_id/types/:type_id/pictures"
    pictures_bis: "/pictures"
    provided_dates: "/users/:login_id/items/:item_id/types/:type_id/contacts/:contact_id/provided_dates"
    types: "/users/:login_id/items/:item_id/types"
    translates: "/translates"
    photos_to_pictures: "/photos_to_pictures"
    countries: "/countries"
    google_contacts_to_contacts: "/google_contacts_to_contacts"
    regions: "/countries/:country_name/regions"
    friends: "/friends"
    user_search_to_contacts: "/user_search_to_contacts"
    users: "/users"
routing_backbonejs:
  API:
    contacts:
      routes:
        "/users/:login_id/items/:item_id/types/:type_id/contacts": "index"
        "/users/:login_id/items/:item_id/types/:type_id/contacts/:id/delete": "destroy"
        "/users/:login_id/items/:item_id/types/:type_id/contacts/:id/edit" : "edit"
        "/users/:login_id/items/:item_id/types/:type_id/contacts/new" : "new"
        "/users/:login_id/contacts/new" : "new_contact"
        "/users/:login_id/contacts" : "index_all"
        "/users/:login_id/contacts/:id/edit" : "edit_all"
        "/users/:login_id/contacts/:id/delete" : "destroy_all"
    friends:
      routes:
        "/friends": "index"
        "/friends/show/:email" : "show"
    items:
      routes:
        "/users/:login_id/items/new": "new_item"
        "/users/:login_id/items/:id/edit" : "edit"
    vcf_to_contacts:
      routes: 
        "/vcf_to_contacts" : "create"
    google_contacts_to_contacts:
      routes:
        "/google_contacts_to_contacts" : "create"
