require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProvidedDatesController do

  # This should return the minimal set of attributes required to create a valid
  # ProvidedDate. As you add validations to ProvidedDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProvidedDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all provided_dates as @provided_dates" do
      provided_date = ProvidedDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:provided_dates).should eq([provided_date])
    end
  end

  describe "GET show" do
    it "assigns the requested provided_date as @provided_date" do
      provided_date = ProvidedDate.create! valid_attributes
      get :show, {:id => provided_date.to_param}, valid_session
      assigns(:provided_date).should eq(provided_date)
    end
  end

  describe "GET new" do
    it "assigns a new provided_date as @provided_date" do
      get :new, {}, valid_session
      assigns(:provided_date).should be_a_new(ProvidedDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested provided_date as @provided_date" do
      provided_date = ProvidedDate.create! valid_attributes
      get :edit, {:id => provided_date.to_param}, valid_session
      assigns(:provided_date).should eq(provided_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProvidedDate" do
        expect {
          post :create, {:provided_date => valid_attributes}, valid_session
        }.to change(ProvidedDate, :count).by(1)
      end

      it "assigns a newly created provided_date as @provided_date" do
        post :create, {:provided_date => valid_attributes}, valid_session
        assigns(:provided_date).should be_a(ProvidedDate)
        assigns(:provided_date).should be_persisted
      end

      it "redirects to the created provided_date" do
        post :create, {:provided_date => valid_attributes}, valid_session
        response.should redirect_to(ProvidedDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provided_date as @provided_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProvidedDate.any_instance.stub(:save).and_return(false)
        post :create, {:provided_date => {}}, valid_session
        assigns(:provided_date).should be_a_new(ProvidedDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProvidedDate.any_instance.stub(:save).and_return(false)
        post :create, {:provided_date => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provided_date" do
        provided_date = ProvidedDate.create! valid_attributes
        # Assuming there are no other provided_dates in the database, this
        # specifies that the ProvidedDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProvidedDate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => provided_date.to_param, :provided_date => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested provided_date as @provided_date" do
        provided_date = ProvidedDate.create! valid_attributes
        put :update, {:id => provided_date.to_param, :provided_date => valid_attributes}, valid_session
        assigns(:provided_date).should eq(provided_date)
      end

      it "redirects to the provided_date" do
        provided_date = ProvidedDate.create! valid_attributes
        put :update, {:id => provided_date.to_param, :provided_date => valid_attributes}, valid_session
        response.should redirect_to(provided_date)
      end
    end

    describe "with invalid params" do
      it "assigns the provided_date as @provided_date" do
        provided_date = ProvidedDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProvidedDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => provided_date.to_param, :provided_date => {}}, valid_session
        assigns(:provided_date).should eq(provided_date)
      end

      it "re-renders the 'edit' template" do
        provided_date = ProvidedDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProvidedDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => provided_date.to_param, :provided_date => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provided_date" do
      provided_date = ProvidedDate.create! valid_attributes
      expect {
        delete :destroy, {:id => provided_date.to_param}, valid_session
      }.to change(ProvidedDate, :count).by(-1)
    end

    it "redirects to the provided_dates list" do
      provided_date = ProvidedDate.create! valid_attributes
      delete :destroy, {:id => provided_date.to_param}, valid_session
      response.should redirect_to(provided_dates_url)
    end
  end

end
